version: "3.7"

services:
  # linux, apache, php container
  app:
  
  # mysql container
  database-cit496:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: 
